name: C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build
      run: |
        mkdir build
        cd build
        g++ ../app.cpp -o main
